Added OpenBank function with support for most major banks
Brandon-T/Reflection pull request #34
Opened 2021-09-29 03:12 UTC by StickToTheScript

Creates a generic function to open most banks. Also tried using two underscores for the utility functions (might require changes, but I'd like to discuss that).

2021-10-13 02:58 UTC, Brandon-T requested changes

2021-10-13 02:58 UTC, Brandon-T commented on Bank.simba
> +    TBankLocation.lUMBRIDGE:
Capitalize `L`?

2021-10-13 02:58 UTC, Brandon-T commented on Bank.simba
>    Result := R_WaitFunction(timeout, 50, @R_BankScreen);
`WaitUntil(R_Bankscreen, 50, timeout)`

2021-10-13 13:06 UTC, StickToTheScript commented on Bank.simba
> +    TBankLocation.lUMBRIDGE:
Good catch! Fixed!

2021-10-13 13:08 UTC, StickToTheScript commented on Bank.simba
>    Result := R_WaitFunction(timeout, 50, @R_BankScreen);
Yea, not a problem! I also took the liberty to change all occurrences of this in the Bank.simba file. As for the other files, I can do those at a different time.

2021-10-16 16:11 UTC, Brandon-T approved these changes

2021-10-16 16:11 UTC, merged